Consolidate all logging to Serilog
tlewis17/MSFSTouchPortalPlugin pull request #51
Opened 2022-02-10 20:37 UTC by mpaperno

* Prettier console output, configurable from `appsettings.json` 
* Live reload of logging settings from `appsettings.json` (w/out restarting plugin)
* Reduce TouchPortalSDK logging level to Warning (was spamming logs with "state updated" messages)
* Also update Microsoft Extensions and SonarAnalyzer to latest versions.

2022-02-10 23:42 UTC, tlewis17 requested changes

2022-02-10 23:57 UTC, mpaperno commented on MSFSTouchPortalPlugin/appsettings.json
> +          "rollingInterval": "Day"
I guess there is...?  Can't actually find documentation but I did find this [Issue](retainedFileCountLimit) which seems to suggest this feature is now available... but there's nothing in the release notes for v5.  Will have to test that I guess.  What I copied over to appsettings was what was in the original config line.  But I agree, a limit would be great, probably just a couple/few old logs need to be retained.

Also the File Sink should probably be wrapped in an Async sink, like in their examples, but I haven't played with that.  But again this is just moving the config out of the code so it's easier to tweak down the line.

2022-02-11 00:17 UTC, mpaperno commented on MSFSTouchPortalPlugin/appsettings.json
> +          "rollingInterval": "Day"
Yep, it works! 7 seemed like a reasonable number, but totally arbitrary.

2022-02-11 00:19 UTC, mpaperno commented
These 2 commits could be squashed, for a cleaner history.

2022-02-11 08:08 UTC, merged